# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protocol/hotel.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'protocol/hotel.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protocol import types_pb2 as protocol_dot_types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14protocol/hotel.proto\x12\x11reservation.hotel\x1a\x14protocol/types.proto\"\xb0\x01\n\x10\x46\x65tchRoomPayload\x12#\n\x06header\x18\x01 \x01(\x0b\x32\x13.reservation.Header\x12\x10\n\x08roomUUID\x18\x02 \x01(\t\x12\x11\n\tstartDate\x18\x03 \x01(\t\x12\x0f\n\x07\x65ndDate\x18\x04 \x01(\t\x12\x0c\n\x04\x62\x65\x64s\x18\x05 \x01(\x05\x12\x0f\n\x07minsize\x18\x06 \x01(\x05\x12\x10\n\x08minprize\x18\x07 \x01(\x05\x12\x10\n\x08maxprice\x18\x08 \x01(\x05\"Z\n\x11\x46\x65tchRoomResponse\x12#\n\x06header\x18\x01 \x01(\x0b\x32\x13.reservation.Header\x12 \n\x05rooms\x18\x02 \x03(\x0b\x32\x11.reservation.Room\"K\n\x12ReservationRequest\x12#\n\x06header\x18\x01 \x01(\x0b\x32\x13.reservation.Header\x12\x10\n\x08roomUUID\x18\x02 \x01(\t\"f\n\x13ReservationResponse\x12#\n\x06header\x18\x01 \x01(\x0b\x32\x13.reservation.Header\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x19\n\x11\x63onfirmation_code\x18\x03 \x01(\t2\xc9\x01\n\x0cHotelService\x12W\n\nFetchRooms\x12#.reservation.hotel.FetchRoomPayload\x1a$.reservation.hotel.FetchRoomResponse\x12`\n\x0fMakeReservation\x12%.reservation.hotel.ReservationRequest\x1a&.reservation.hotel.ReservationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protocol.hotel_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FETCHROOMPAYLOAD']._serialized_start=66
  _globals['_FETCHROOMPAYLOAD']._serialized_end=242
  _globals['_FETCHROOMRESPONSE']._serialized_start=244
  _globals['_FETCHROOMRESPONSE']._serialized_end=334
  _globals['_RESERVATIONREQUEST']._serialized_start=336
  _globals['_RESERVATIONREQUEST']._serialized_end=411
  _globals['_RESERVATIONRESPONSE']._serialized_start=413
  _globals['_RESERVATIONRESPONSE']._serialized_end=515
  _globals['_HOTELSERVICE']._serialized_start=518
  _globals['_HOTELSERVICE']._serialized_end=719
# @@protoc_insertion_point(module_scope)
