# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protocol/types.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'protocol/types.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14protocol/types.proto\x12\x0breservation\"\x8f\x01\n\x07\x41\x64\x64ress\x12\x0f\n\x07\x63ountry\x18\x01 \x01(\t\x12\x0c\n\x04\x63ity\x18\x02 \x01(\t\x12\x0e\n\x06street\x18\x03 \x01(\t\x12\x0e\n\x06number\x18\x04 \x01(\t\x12\x15\n\rlocation_hint\x18\x05 \x01(\t\x12.\n\x0cgps_position\x18\x06 \x01(\x0b\x32\x18.reservation.GPSPosition\"\'\n\x06Header\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"2\n\x0bGPSPosition\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01\"G\n\x04Room\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04\x62\x65\x64s\x18\x02 \x01(\x05\x12\x12\n\nbase_price\x18\x03 \x01(\x01\x12\x11\n\timage_url\x18\x04 \x01(\t\"[\n\x05Offer\x12\n\n\x02id\x18\x01 \x01(\t\x12\x1f\n\x04room\x18\x02 \x01(\x0b\x32\x11.reservation.Room\x12\x16\n\x0e\x61vailable_date\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x01\"_\n\x08\x43ustomer\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t\x12,\n\x0b\x63redit_card\x18\x03 \x01(\x0b\x32\x17.reservation.CreditCard\"B\n\nCreditCard\x12\x0e\n\x06number\x18\x01 \x01(\t\x12\x17\n\x0f\x65xpiration_date\x18\x02 \x01(\t\x12\x0b\n\x03\x63vv\x18\x03 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protocol.types_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDRESS']._serialized_start=38
  _globals['_ADDRESS']._serialized_end=181
  _globals['_HEADER']._serialized_start=183
  _globals['_HEADER']._serialized_end=222
  _globals['_GPSPOSITION']._serialized_start=224
  _globals['_GPSPOSITION']._serialized_end=274
  _globals['_ROOM']._serialized_start=276
  _globals['_ROOM']._serialized_end=347
  _globals['_OFFER']._serialized_start=349
  _globals['_OFFER']._serialized_end=440
  _globals['_CUSTOMER']._serialized_start=442
  _globals['_CUSTOMER']._serialized_end=537
  _globals['_CREDITCARD']._serialized_start=539
  _globals['_CREDITCARD']._serialized_end=605
# @@protoc_insertion_point(module_scope)
